#!/bin/bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2026 Vasiliy Kovalev <kovalev@altlinux.org>
#
# graft-oot-xtables-addons.sh -- Grafts kernel-modules-xtables-addons-6.12
# into net/netfilter/xtables-addons/ in the kernel source tree so the
# extensions can be built =y and covered by KCOV.
#
# The script replaces the original Kbuild files (which require the out-of-tree
# mconfig generated by autoconf) with kernel-native Kbuild files that use
# CONFIG_ symbols set by 02-build-kernel.sh.
#
# Source: git://git.altlinux.org/gears/x/xtables-addons.git  ref: p11
#
# Usage (called automatically by 02-build-kernel.sh):
#   KERNEL_DIR=/path/to/kernel ./scripts/graft-oot-xtables-addons.sh
#   NO_CLONE=1 ./scripts/graft-oot-xtables-addons.sh  (skip git clone)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Use KERNEL_DIR from environment (set by 01-setup-env.sh / 02-build-kernel.sh).
# Fall back to sourcing 01-setup-env.sh if called directly.
if [ -z "${KERNEL_DIR:-}" ]; then
    source "$SCRIPT_DIR/01-setup-env.sh" >/dev/null
fi
: "${KERNEL_DIR:?KERNEL_DIR is not set}"

: "${TMPDIR:=/tmp/graft-oot}"

GIT_URL="git://git.altlinux.org/gears/x/xtables-addons.git"
GIT_REF="p11"
SRC="$TMPDIR/xtables-addons"
DST="$KERNEL_DIR/net/netfilter/xtables-addons"

log() { echo "[graft xtables-addons] $*"; }
die() { echo "[graft xtables-addons] ERROR: $*" >&2; exit 1; }

for cmd in git rsync; do
    command -v "$cmd" &>/dev/null || die "required: $cmd"
done
[ -f "$KERNEL_DIR/Kconfig" ] || die "not a kernel source tree: $KERNEL_DIR"

mkdir -p "$TMPDIR"

# 1. Clone or update
if [ "${NO_CLONE:-0}" = "1" ] && [ -d "$SRC/.git" ]; then
    log "NO_CLONE=1, skipping clone"
elif [ -d "$SRC/.git" ]; then
    log "updating $SRC"
    git -C "$SRC" fetch --depth=1 origin "$GIT_REF"
    git -C "$SRC" checkout FETCH_HEAD
else
    log "cloning $GIT_URL ref=$GIT_REF -> $SRC"
    git clone --depth=1 --branch "$GIT_REF" "$GIT_URL" "$SRC"
fi

# 2. Find the extensions/ directory (Gear may ship a tarball)
ROOT="$SRC"
if [ ! -d "$ROOT/extensions" ]; then
    tarball=$(ls "$SRC"/*.tar.* 2>/dev/null | head -1 || true)
    [ -n "$tarball" ] || die "cannot find extensions/ in $SRC"
    log "unpacking $tarball"
    tar xf "$tarball" -C "$TMPDIR"
    ROOT=$(find "$TMPDIR" -maxdepth 3 -name "extensions" -printf '%h\n' 2>/dev/null | head -1)
    [ -d "$ROOT/extensions" ] || die "extensions/ not found after unpack"
fi

# 3. Copy sources into the kernel tree
log "grafting xtables-addons -> $DST"
mkdir -p "$DST"
rsync -a --delete \
    --exclude='*.o' --exclude='*.ko' --exclude='*.mod.*' \
    --exclude='*.cmd' --exclude='.git' \
    "$ROOT/extensions/" "$DST/"

# 4. Install UAPI headers so syz-extract can regenerate .const files
UAPI="$KERNEL_DIR/include/uapi/linux/netfilter"
mkdir -p "$UAPI"
find "$DST" -maxdepth 2 -name 'xt_*.h' | while read -r h; do
    base=$(basename "$h")
    [ -f "$UAPI/$base" ] || { cp "$h" "$UAPI/"; log "header: $base"; }
done

# 5. Replace top-level Kbuild
#
# The original Kbuild uses "include ${XA_ABSTOPSRCDIR}/mconfig" which is
# generated by the xtables-addons autoconf build system and is not available
# for in-kernel builds. We replace it with a kernel-native Kbuild that uses
# CONFIG_ symbols set by 02-build-kernel.sh.
#
# Object lines are emitted only for extensions whose source is actually
# present: ALT does not ship every upstream extension (xt_ipp2p.c is absent in
# p11), and an obj-y line without a matching .c breaks the kernel build.
#
# SYSRQ target is excluded: it triggers a real sysrq action in-guest.
#
# CONFIG symbol | source path (relative to $DST) | object
XA_EXTENSIONS="
NETFILTER_XT_TARGET_ACCOUNT|ACCOUNT/xt_ACCOUNT.c|ACCOUNT/
NETFILTER_XT_MATCH_PKNOCK|pknock/xt_pknock.c|pknock/
NETFILTER_XT_TARGET_CHAOS|xt_CHAOS.c|xt_CHAOS.o
NETFILTER_XT_TARGET_DELUDE|xt_DELUDE.c|xt_DELUDE.o
NETFILTER_XT_TARGET_DHCPMAC|xt_DHCPMAC.c|xt_DHCPMAC.o
NETFILTER_XT_TARGET_DNETMAP|xt_DNETMAP.c|xt_DNETMAP.o
NETFILTER_XT_TARGET_ECHO|xt_ECHO.c|xt_ECHO.o
NETFILTER_XT_TARGET_IPMARK|xt_IPMARK.c|xt_IPMARK.o
NETFILTER_XT_TARGET_LOGMARK|xt_LOGMARK.c|xt_LOGMARK.o
NETFILTER_XT_TARGET_PROTO|xt_PROTO.c|xt_PROTO.o
NETFILTER_XT_TARGET_TARPIT|xt_TARPIT.c|xt_TARPIT.o
NETFILTER_XT_MATCH_CONDITION|xt_condition.c|xt_condition.o
NETFILTER_XT_MATCH_FUZZY|xt_fuzzy.c|xt_fuzzy.o
NETFILTER_XT_MATCH_GEOIP|xt_geoip.c|xt_geoip.o
NETFILTER_XT_MATCH_ASN|xt_asn.c|xt_asn.o
NETFILTER_XT_MATCH_IFACE|xt_iface.c|xt_iface.o
NETFILTER_XT_MATCH_IPP2P|xt_ipp2p.c|xt_ipp2p.o
NETFILTER_XT_MATCH_IPV4OPTIONS|xt_ipv4options.c|xt_ipv4options.o
NETFILTER_XT_MATCH_LENGTH2|xt_length2.c|xt_length2.o
NETFILTER_XT_MATCH_LSCAN|xt_lscan.c|xt_lscan.o
NETFILTER_XT_MATCH_PSD|xt_psd.c|xt_psd.o
NETFILTER_XT_MATCH_QUOTA2|xt_quota2.c|xt_quota2.o
"

log "writing in-kernel Kbuild -> $DST/Kbuild"
{
    echo "# In-kernel Kbuild for xtables-addons extensions."
    echo "# Generated by graft-oot-xtables-addons.sh -- do not edit."
    echo 'ccflags-y := -I$(src)'
    echo
    printf '%s\n' "$XA_EXTENSIONS" | while IFS='|' read -r sym src obj; do
        [ -n "$sym" ] || continue
        if [ -e "$DST/$src" ]; then
            printf 'obj-$(CONFIG_%s) += %s\n' "$sym" "$obj"
        else
            echo "[graft xtables-addons] not shipped, skipping: $src" >&2
        fi
    done
} > "$DST/Kbuild"

# 6b. Generate Kconfig for xtables-addons
# Required so ./scripts/config -e NETFILTER_XT_MATCH_* symbols are recognized.
log "writing Kconfig -> $DST/Kconfig"
cat > "$DST/Kconfig" << 'KCONFIG'
# Kconfig for xtables-addons grafted into net/netfilter/xtables-addons/
# All options default to y for KCOV attribution.

menu "xtables-addons matches and targets (grafted)"
	depends on NETFILTER_XTABLES

config NETFILTER_XT_MATCH_CONDITION
	tristate '"condition" match'
	depends on PROC_FS
	default y

config NETFILTER_XT_MATCH_QUOTA2
	tristate '"quota2" match'
	depends on PROC_FS
	default y

config NETFILTER_XT_MATCH_FUZZY
	tristate '"fuzzy" match'
	default y

config NETFILTER_XT_MATCH_IFACE
	tristate '"iface" match'
	default y

config NETFILTER_XT_MATCH_LENGTH2
	tristate '"length2" match'
	default y

config NETFILTER_XT_MATCH_IPP2P
	tristate '"ipp2p" match'
	depends on TEXTSEARCH
	default y

config NETFILTER_XT_MATCH_PSD
	tristate '"psd" match'
	default y

config NETFILTER_XT_MATCH_GEOIP
	tristate '"geoip" match'
	default y

config NETFILTER_XT_MATCH_ASN
	tristate '"asn" match'
	default y

config NETFILTER_XT_MATCH_IPV4OPTIONS
	tristate '"ipv4options" match'
	default y

config NETFILTER_XT_MATCH_LSCAN
	tristate '"lscan" match'
	default y

config NETFILTER_XT_MATCH_PKNOCK
	tristate '"pknock" match'
	default y

config NETFILTER_XT_TARGET_TARPIT
	tristate '"TARPIT" target'
	depends on IP_NF_FILTER
	default y

config NETFILTER_XT_TARGET_CHAOS
	tristate '"CHAOS" target'
	depends on NETFILTER_XT_TARGET_TARPIT || NETFILTER_XT_TARGET_DELUDE
	default y

config NETFILTER_XT_TARGET_DELUDE
	tristate '"DELUDE" target'
	depends on IP_NF_FILTER
	default y

config NETFILTER_XT_TARGET_ECHO
	tristate '"ECHO" target'
	default y

config NETFILTER_XT_TARGET_SYSRQ
	tristate '"SYSRQ" target (excluded from fuzzing: triggers real sysrq)'
	depends on MAGIC_SYSRQ
	default n

config NETFILTER_XT_TARGET_IPMARK
	tristate '"IPMARK" target'
	depends on IP_NF_MANGLE
	default y

config NETFILTER_XT_TARGET_LOGMARK
	tristate '"LOGMARK" target'
	default y

config NETFILTER_XT_TARGET_PROTO
	tristate '"PROTO" target'
	depends on IP_NF_MANGLE
	default y

config NETFILTER_XT_TARGET_DHCPMAC
	tristate '"DHCPMAC" target'
	depends on IP_NF_MANGLE
	default y

config NETFILTER_XT_TARGET_DNETMAP
	tristate '"DNETMAP" target'
	depends on IP_NF_NAT
	default y

config NETFILTER_XT_TARGET_ACCOUNT
	tristate '"ACCOUNT" target'
	depends on IP_NF_NAT && PROC_FS
	default y

endmenu
KCONFIG

# 6. Fix ACCOUNT/Kbuild
#
# Original: "obj-m += xt_ACCOUNT.o" -- builds as module, not built-in.
# Replace with CONFIG_-based in-kernel Kbuild.
log "writing in-kernel ACCOUNT/Kbuild"
cat > "$DST/ACCOUNT/Kbuild" << 'KBUILD'
ccflags-y += -I$(src)/..
obj-$(CONFIG_NETFILTER_XT_TARGET_ACCOUNT) += xt_ACCOUNT.o
KBUILD

# 7. Fix pknock/Kbuild
log "writing in-kernel pknock/Kbuild"
cat > "$DST/pknock/Kbuild" << 'KBUILD'
ccflags-y += -I$(src)/..
obj-$(CONFIG_NETFILTER_XT_MATCH_PKNOCK) += xt_pknock.o
KBUILD

# 8. Wire into net/netfilter/
NF_K="$KERNEL_DIR/net/netfilter/Kconfig"
grep -q "xtables-addons" "$NF_K" 2>/dev/null || \
    printf '\n# xtables-addons (grafted)\nsource "net/netfilter/xtables-addons/Kconfig"\n' >> "$NF_K"

NF_M="$KERNEL_DIR/net/netfilter/Makefile"
grep -q "xtables-addons" "$NF_M" 2>/dev/null || \
    printf '\n# xtables-addons (grafted)\nobj-y += xtables-addons/\n' >> "$NF_M"

# 8. Install xt_addons_compat.h so syz-extract can compile xtables-addons
# UAPI headers that use userspace types (uint8_t, u_int8_t, ETH_ALEN,
# IFNAMSIZ, struct in6_addr, struct nf_nat_range) unavailable under
# syz-extract's -nostdinc -D__KERNEL__ compilation flags.
COMPAT_H="$KERNEL_DIR/include/uapi/linux/netfilter/xt_addons_compat.h"
if [ ! -f "$COMPAT_H" ]; then
    log "installing $COMPAT_H"
    cat > "$COMPAT_H" << 'COMPAT_HEADER'
/* SPDX-License-Identifier: GPL-2.0 */
/*
 * xt_addons_compat.h: kernel-context compat types for xtables-addons UAPI.
 * Created by graft-oot-xtables-addons.sh, included first in netfilter_xt_addons.txt.
 */
#ifndef _XT_ADDONS_COMPAT_H
#define _XT_ADDONS_COMPAT_H

#define ACCOUNT_TABLE_NAME_LEN 32
#define XT_SO_LEVELMAP_BYTES 40

#include <linux/types.h>
#include <linux/if_ether.h>
#include <linux/if.h>
#include <linux/in6.h>
#include <net/cipso_ipv4.h>
#include <uapi/linux/ip.h>
#include <uapi/linux/netfilter/nf_nat.h>
#ifndef __uint8_t_defined
typedef __u8  uint8_t;
typedef __u16 uint16_t;
typedef __u32 uint32_t;
typedef __u64 uint64_t;
#define __uint8_t_defined
#endif
#ifndef __u_int8_t_defined
typedef __u8  u_int8_t;
typedef __u16 u_int16_t;
typedef __u32 u_int32_t;
typedef __u64 u_int64_t;
#define __u_int8_t_defined
#endif
#endif /* _XT_ADDONS_COMPAT_H */
COMPAT_HEADER
fi
log "done"
