#!/bin/bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2026 Vasiliy Kovalev <kovalev@altlinux.org>
#
# graft-oot-ipt-so.sh -- Grafts kernel-modules-ipt-so-6.12 (the xt_so
# iptables match for CIPSO/RFC1108-Astra security labels) into the kernel
# source tree alongside the xtables-addons extensions.
#
# xt_so.c is placed in net/netfilter/xtables-addons/ and referenced from
# its own directory, net/netfilter/ipt-so/, with its own Kbuild and Kconfig.
#
# It used to share net/netfilter/xtables-addons/ with the other grafted modules,
# which made the coverage report ambiguous: xt_so.c is a separate ALT package
# and belongs on its own line, not mixed in with xtables-addons.
#
# Source: git://git.altlinux.org/gears/i/ipt-so.git  ref: p11
#
# Usage (called automatically by 02-build-kernel.sh):
#   KERNEL_DIR=/path/to/kernel ./scripts/graft-oot-ipt-so.sh
#   NO_CLONE=1 ./scripts/graft-oot-ipt-so.sh  (skip git clone)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ -z "${KERNEL_DIR:-}" ]; then
    source "$SCRIPT_DIR/01-setup-env.sh" >/dev/null
fi
: "${KERNEL_DIR:?KERNEL_DIR is not set}"

: "${TMPDIR:=/tmp/graft-oot}"

GIT_URL="git://git.altlinux.org/gears/i/ipt-so.git"
GIT_REF="p11"
SRC="$TMPDIR/ipt-so"
DST="$KERNEL_DIR/net/netfilter/ipt-so"

log() { echo "[graft ipt-so] $*"; }
die() { echo "[graft ipt-so] ERROR: $*" >&2; exit 1; }

command -v git &>/dev/null || die "required: git"
[ -f "$KERNEL_DIR/Kconfig" ] || die "not a kernel source tree: $KERNEL_DIR"
mkdir -p "$DST"

mkdir -p "$TMPDIR"

# 1. Clone or update
if [ "${NO_CLONE:-0}" = "1" ] && [ -d "$SRC/.git" ]; then
    log "NO_CLONE=1, skipping clone"
elif [ -d "$SRC/.git" ]; then
    log "updating $SRC"
    git -C "$SRC" fetch --depth=1 origin "$GIT_REF"
    git -C "$SRC" checkout FETCH_HEAD
else
    log "cloning $GIT_URL ref=$GIT_REF -> $SRC"
    git clone --depth=1 --branch "$GIT_REF" "$GIT_URL" "$SRC"
fi

# 2. Copy xt_so.c into its own directory
SO_C=$(find "$SRC" -name 'xt_so.c' 2>/dev/null | head -1)
[ -n "$SO_C" ] || die "xt_so.c not found in $SRC"
log "grafting xt_so.c -> $DST/"
cp "$SO_C" "$DST/"

# Patch xt_so.c: VERSION is set by "git describe" in the out-of-tree Makefile
# (VERSION = $(shell git -C $M describe --dirty)) and is unavailable in the
# kernel build environment. Replace with a literal string.
sed -i 's|^#define XT_SO_VERSION VERSION$|#define XT_SO_VERSION "in-kernel"|' \
    "$DST/xt_so.c"
log "patched xt_so.c: XT_SO_VERSION set to literal string"

# 3. Install xt_so.h
SO_H=$(find "$SRC" -name 'xt_so.h' 2>/dev/null | head -1)
if [ -n "$SO_H" ]; then
    # Place alongside xt_so.c so "#include \"xt_so.h\"" resolves at build time.
    cp "$SO_H" "$DST/"
    log "installed xt_so.h -> $DST/"
    # Also install into UAPI for syz-extract and userspace tools.
    UAPI="$KERNEL_DIR/include/uapi/linux/netfilter"
    mkdir -p "$UAPI"
    cp "$SO_H" "$UAPI/"
    log "installed xt_so.h -> include/uapi/linux/netfilter/"
fi

# 4. Write Kbuild and Kconfig for the new directory
log "writing $DST/Kbuild"
cat > "$DST/Kbuild" << 'KBUILD'
# In-kernel Kbuild for ipt-so.
# Generated by graft-oot-ipt-so.sh -- do not edit.
ccflags-y := -I$(src)

obj-$(CONFIG_NETFILTER_XT_MATCH_SO) += xt_so.o
KBUILD

log "writing $DST/Kconfig"
cat > "$DST/Kconfig" << 'SOCONF'
# Generated by graft-oot-ipt-so.sh -- do not edit.
menu "ipt-so (out-of-tree)"

config NETFILTER_XT_MATCH_SO
	tristate "so: CIPSO/RFC1108-Astra security-label match (ipt-so)"
	depends on IP_NF_SECURITY && NETLABEL
	default y

endmenu
SOCONF

# 5. Wire the directory into net/netfilter
NF_MAKEFILE="$KERNEL_DIR/net/netfilter/Makefile"
if ! grep -q '^obj-y += ipt-so/' "$NF_MAKEFILE"; then
    printf '\n# out-of-tree, grafted by graft-oot-ipt-so.sh\nobj-y += ipt-so/\n' >> "$NF_MAKEFILE"
    log "added ipt-so/ to net/netfilter/Makefile"
fi

NF_KCONFIG="$KERNEL_DIR/net/netfilter/Kconfig"
if ! grep -q 'net/netfilter/ipt-so/Kconfig' "$NF_KCONFIG"; then
    printf '\nsource "net/netfilter/ipt-so/Kconfig"\n' >> "$NF_KCONFIG"
    log "added ipt-so/Kconfig to net/netfilter/Kconfig"
fi

log "done"
log ""
log "Note: register a CIPSO DOI in the guest to allow labelled test packets"
log "to reach so_mt() without being dropped by the IP receive path:"
log "  netlabelctl cipso add pass doi:1 tags:1"
log "  netlabelctl unlbl setdef address:0.0.0.0/0 label:unlabelled"
